local config = 
{
	[1001] = 
	{
		name = 'Acid',
		icon = 'acid',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1002] = 
	{
		name = 'Alloy',
		icon = 'alloy',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.04,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1003] = 
	{
		name = 'Bandana',
		icon = 'bandana',
		rarity = 1,
		base_price = 30,
		attr = 
		{
			MaxHp = -1,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1004] = 
	{
		name = 'BigArms',
		icon = 'big_arms',
		rarity = 1,
		base_price = 8,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1005] = 
	{
		name = 'BlackBelt',
		icon = 'black_belt',
		rarity = 1,
		base_price = 25,
		attr = 
		{
			MaxHp = 5,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1006] = 
	{
		name = 'Book',
		icon = 'book',
		rarity = 1,
		base_price = 30,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1007] = 
	{
		name = 'BowlerHat',
		icon = 'bowler_hat',
		rarity = 1,
		base_price = 15,
		attr = 
		{
			MaxHp = 3,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1008] = 
	{
		name = 'Charcoal',
		icon = 'charcoal',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 2,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1009] = 
	{
		name = 'Cape',
		icon = 'cape',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = -1,
			MeleeDamage = 1,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.03,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1010] = 
	{
		name = 'Charcoal',
		icon = 'charcoal',
		rarity = 1,
		base_price = 15,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.1,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2001] = 
	{
		name = 'Coffee',
		icon = 'coffee',
		rarity = 2,
		base_price = 65,
		attr = 
		{
			MaxHp = 8,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = -0.04,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2002] = 
	{
		name = 'Cog',
		icon = 'cog',
		rarity = 2,
		base_price = 55,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.1,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2003] = 
	{
		name = 'Coupon',
		icon = 'coupon',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = 0.05,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2004] = 
	{
		name = 'Crown',
		icon = 'crown',
		rarity = 2,
		base_price = 50,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2005] = 
	{
		name = 'Cyberball',
		icon = 'cyberball',
		rarity = 2,
		base_price = 40,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.02,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2006] = 
	{
		name = 'Diploma',
		icon = 'diploma',
		rarity = 2,
		base_price = 35,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2007] = 
	{
		name = 'EnergyBracelet',
		icon = 'energy_bracelet',
		rarity = 2,
		base_price = 40,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = -0.03,
			Dodge = 0.0,
			Speed = 0.05,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2008] = 
	{
		name = 'ExplosiveTurret',
		icon = 'explosive_turret',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2009] = 
	{
		name = 'Exoskeleton',
		icon = 'exoskeleton',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2010] = 
	{
		name = 'HeavyBullets',
		icon = 'heavy_bullets',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3001] = 
	{
		name = 'FuelTank',
		icon = 'fuel_tank',
		rarity = 3,
		base_price = 85,
		attr = 
		{
			MaxHp = 8,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3002] = 
	{
		name = 'GamblingToken',
		icon = 'gambling_token',
		rarity = 3,
		base_price = 80,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 3,
			RangedDamage = 3,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = -0.06,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3003] = 
	{
		name = 'Glasses',
		icon = 'glasses',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = -0.05,
			CritChance = -0.03,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3004] = 
	{
		name = 'Handcuffs',
		icon = 'handcuffs',
		rarity = 3,
		base_price = 65,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.06,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3005] = 
	{
		name = 'JetPack',
		icon = 'jet_pack',
		rarity = 3,
		base_price = 65,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.1,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3006] = 
	{
		name = 'Landmines',
		icon = 'landmines',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -3,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3007] = 
	{
		name = 'LaserTurret',
		icon = 'laser_turret',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -3,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3008] = 
	{
		name = 'Scope',
		icon = 'scope',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -3,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3009] = 
	{
		name = 'MedicalTurret',
		icon = 'medical_turret',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -3,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3010] = 
	{
		name = 'Medal',
		icon = 'medal',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -3,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4001] = 
	{
		name = 'Medikit',
		icon = 'medikit',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 5,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = 0.0,
			Speed = 0.05,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4002] = 
	{
		name = 'NightGoggles',
		icon = 'night_goggles',
		rarity = 4,
		base_price = 105,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 10,
			RangedDamage = 5,
			Armor = -2,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.05,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4003] = 
	{
		name = 'Panda',
		icon = 'panda',
		rarity = 4,
		base_price = 110,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = -2,
			RangedDamage = -2,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.2,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4004] = 
	{
		name = 'TrianglePower',
		icon = 'triangle_power',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 5,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = -0.1,
			CritChance = -0.05,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4005] = 
	{
		name = 'Turret',
		icon = 'turret',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = -6,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -2,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.1,
			Speed = 0.15,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4006] = 
	{
		name = 'WanderingBot',
		icon = 'wandering_bot',
		rarity = 4,
		base_price = 115,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 15,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = -0.03,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4007] = 
	{
		name = 'RobotArm',
		icon = 'robot_arm',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4008] = 
	{
		name = 'Toolbox',
		icon = 'toolbox',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = -3,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = -2,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.15,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4009] = 
	{
		name = 'Torture',
		icon = 'torture',
		rarity = 4,
		base_price = 105,
		attr = 
		{
			MaxHp = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = -0.08,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4010] = 
	{
		name = 'WarriorHelmet',
		icon = 'warrior_helmet',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = 12,
			MeleeDamage = 0,
			RangedDamage = 0,
			Armor = 0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			LifeSteal = 0.0,
		},
		limit = 0,
		unlocked = 0,
	},
}
return config