local config = 
{
	[1001] = 
	{
		name = 'item1',
		icon = 'item1',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.02,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = -2,
		},
		limit = 0,
		unlocked = 0,
	},
	[1002] = 
	{
		name = 'item2',
		icon = 'item2',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = -6,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.04,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1003] = 
	{
		name = 'item3',
		icon = 'item3',
		rarity = 1,
		base_price = 30,
		attr = 
		{
			MaxHp = -1,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 2,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1004] = 
	{
		name = 'item4',
		icon = 'item4',
		rarity = 1,
		base_price = 8,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 1,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1005] = 
	{
		name = 'item5',
		icon = 'item5',
		rarity = 1,
		base_price = 25,
		attr = 
		{
			MaxHp = 5,
			HPRegeneration = -1,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1006] = 
	{
		name = 'item6',
		icon = 'item6',
		rarity = 1,
		base_price = 30,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = -1,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.02,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1007] = 
	{
		name = 'item7',
		icon = 'item7',
		rarity = 1,
		base_price = 15,
		attr = 
		{
			MaxHp = 3,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.1,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1008] = 
	{
		name = 'item8',
		icon = 'item8',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 2,
			RangedDamage = 0,
			ElementalDamage = 1,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = -2,
		},
		limit = 0,
		unlocked = 0,
	},
	[1009] = 
	{
		name = 'item9',
		icon = 'item9',
		rarity = 1,
		base_price = 20,
		attr = 
		{
			MaxHp = -1,
			HPRegeneration = 0,
			MeleeDamage = 1,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.03,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[1010] = 
	{
		name = 'item10',
		icon = 'item10',
		rarity = 1,
		base_price = 15,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.02,
			AttackSpeed = 0.1,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2001] = 
	{
		name = 'item11',
		icon = 'item11',
		rarity = 2,
		base_price = 65,
		attr = 
		{
			MaxHp = 8,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = -0.04,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2002] = 
	{
		name = 'item12',
		icon = 'item12',
		rarity = 2,
		base_price = 55,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 20,
			Armor = 0,
			Luck = 0,
			LifeSteal = -0.02,
			Damage = 0.0,
			AttackSpeed = 0.1,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2003] = 
	{
		name = 'item13',
		icon = 'item13',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = -15,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = 0.05,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2004] = 
	{
		name = 'item14',
		icon = 'item14',
		rarity = 2,
		base_price = 50,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 2,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.02,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = -6,
		},
		limit = 0,
		unlocked = 0,
	},
	[2005] = 
	{
		name = 'item15',
		icon = 'item15',
		rarity = 2,
		base_price = 40,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 2,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 2,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.02,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2006] = 
	{
		name = 'item16',
		icon = 'item16',
		rarity = 2,
		base_price = 35,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = -0.04,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 4,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2007] = 
	{
		name = 'item17',
		icon = 'item17',
		rarity = 2,
		base_price = 40,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = -0.03,
			Dodge = 0.0,
			Speed = 0.05,
			Engineering = 3,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[2008] = 
	{
		name = 'item18',
		icon = 'item18',
		rarity = 2,
		base_price = 45,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = -12,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.12,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3001] = 
	{
		name = 'item19',
		icon = 'item19',
		rarity = 3,
		base_price = 85,
		attr = 
		{
			MaxHp = 8,
			HPRegeneration = 3,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = -8,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3002] = 
	{
		name = 'item20',
		icon = 'item20',
		rarity = 3,
		base_price = 80,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 3,
			RangedDamage = 3,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = -0.06,
			Speed = 0.0,
			Engineering = 3,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3003] = 
	{
		name = 'item21',
		icon = 'item21',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 15,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = -0.05,
			CritChance = -0.03,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 18,
		},
		limit = 0,
		unlocked = 0,
	},
	[3004] = 
	{
		name = 'item22',
		icon = 'item22',
		rarity = 3,
		base_price = 65,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 20,
			LifeSteal = -0.02,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.06,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3005] = 
	{
		name = 'item23',
		icon = 'item23',
		rarity = 3,
		base_price = 65,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = -8,
			LifeSteal = 0.03,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.1,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[3006] = 
	{
		name = 'item24',
		icon = 'item24',
		rarity = 3,
		base_price = 75,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = -3,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.25,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4001] = 
	{
		name = 'item25',
		icon = 'item25',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = -2,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 5,
			Luck = 0,
			LifeSteal = -0.02,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.05,
			Dodge = 0.0,
			Speed = 0.05,
			Engineering = 5,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4002] = 
	{
		name = 'item26',
		icon = 'item26',
		rarity = 4,
		base_price = 105,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 10,
			RangedDamage = 5,
			ElementalDamage = 0,
			Range = 0,
			Armor = -2,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.05,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4003] = 
	{
		name = 'item27',
		icon = 'item27',
		rarity = 4,
		base_price = 110,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = -2,
			RangedDamage = -2,
			ElementalDamage = -2,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.05,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.2,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4004] = 
	{
		name = 'item28',
		icon = 'item28',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 5,
			ElementalDamage = 0,
			Range = 10,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.1,
			AttackSpeed = -0.1,
			CritChance = -0.05,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4005] = 
	{
		name = 'item29',
		icon = 'item29',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = -6,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = -2,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.1,
			Speed = 0.15,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4006] = 
	{
		name = 'item30',
		icon = 'item30',
		rarity = 4,
		base_price = 115,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 2,
			MeleeDamage = 15,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = -0.08,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = -0.03,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4007] = 
	{
		name = 'item31',
		icon = 'item31',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 8,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = -15,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4008] = 
	{
		name = 'item32',
		icon = 'item32',
		rarity = 4,
		base_price = 90,
		attr = 
		{
			MaxHp = -3,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 50,
			Armor = -2,
			Luck = 0,
			LifeSteal = 0.0,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = 0.15,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4009] = 
	{
		name = 'item33',
		icon = 'item33',
		rarity = 4,
		base_price = 105,
		attr = 
		{
			MaxHp = 0,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 0,
			LifeSteal = 0.05,
			Damage = 0.0,
			AttackSpeed = 0.0,
			CritChance = -0.08,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4010] = 
	{
		name = 'item34',
		icon = 'item34',
		rarity = 4,
		base_price = 100,
		attr = 
		{
			MaxHp = 12,
			HPRegeneration = 0,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 0,
			Luck = 25,
			LifeSteal = 0.0,
			Damage = -0.12,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.0,
			Speed = 0.0,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
	[4011] = 
	{
		name = 'item35',
		icon = 'item35',
		rarity = 4,
		base_price = 85,
		attr = 
		{
			MaxHp = 3,
			HPRegeneration = 1,
			MeleeDamage = 0,
			RangedDamage = 0,
			ElementalDamage = 0,
			Range = 0,
			Armor = 1,
			Luck = 5,
			LifeSteal = 0.01,
			Damage = 0.03,
			AttackSpeed = 0.0,
			CritChance = 0.0,
			Dodge = 0.03,
			Speed = 0.03,
			Engineering = 0,
			Harvesting = 0,
		},
		limit = 0,
		unlocked = 0,
	},
}
return config