local config = 
{
	[10101] = 
	{
		name = 'Pistol',
		icon = 'pistol',
		model = 'Pistol',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.3,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 50.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10102] = 
	{
		name = 'Pistol',
		icon = 'pistol',
		model = 'Pistol',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.3,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 50.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10103] = 
	{
		name = 'Pistol',
		icon = 'pistol',
		model = 'Pistol',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.3,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 50.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10104] = 
	{
		name = 'Pistol',
		icon = 'pistol',
		model = 'Pistol',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.3,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 50.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10201] = 
	{
		name = 'Shotgun',
		icon = 'shotgun',
		model = 'Shotgun',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 10,
			BulletSpeed = 35.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10202] = 
	{
		name = 'Shotgun',
		icon = 'shotgun',
		model = 'Shotgun',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 10,
			BulletSpeed = 35.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10203] = 
	{
		name = 'Shotgun',
		icon = 'shotgun',
		model = 'Shotgun',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 10,
			BulletSpeed = 35.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10204] = 
	{
		name = 'Shotgun',
		icon = 'shotgun',
		model = 'Shotgun',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 10,
			BulletSpeed = 35.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10301] = 
	{
		name = 'SMG',
		icon = 'smg',
		model = 'SMG',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.3,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 40.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10302] = 
	{
		name = 'SMG',
		icon = 'smg',
		model = 'SMG',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.3,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 40.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10303] = 
	{
		name = 'SMG',
		icon = 'smg',
		model = 'SMG',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.3,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 40.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10304] = 
	{
		name = 'SMG',
		icon = 'smg',
		model = 'SMG',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.3,
			CritChance = 0.2,
			Range = 50,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 40.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10401] = 
	{
		name = 'Sniper',
		icon = 'sniper',
		model = 'Sniper',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10402] = 
	{
		name = 'Sniper',
		icon = 'sniper',
		model = 'Sniper',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10403] = 
	{
		name = 'Sniper',
		icon = 'sniper',
		model = 'Sniper',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10404] = 
	{
		name = 'Sniper',
		icon = 'sniper',
		model = 'Sniper',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.0,
			CritChance = 0.2,
			Range = 50,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10501] = 
	{
		name = 'Minigun',
		icon = 'minigun',
		model = 'Minigun',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.25,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 45.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10502] = 
	{
		name = 'Minigun',
		icon = 'minigun',
		model = 'Minigun',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.25,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 45.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10503] = 
	{
		name = 'Minigun',
		icon = 'minigun',
		model = 'Minigun',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.25,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 45.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10504] = 
	{
		name = 'Minigun',
		icon = 'minigun',
		model = 'Minigun',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 0.25,
			CritChance = 0.2,
			Range = 50,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 45.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10601] = 
	{
		name = 'Rocket',
		icon = 'rocket',
		model = 'Rocket',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10602] = 
	{
		name = 'Rocket',
		icon = 'rocket',
		model = 'Rocket',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10603] = 
	{
		name = 'Rocket',
		icon = 'rocket',
		model = 'Rocket',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10604] = 
	{
		name = 'Rocket',
		icon = 'rocket',
		model = 'Rocket',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.2,
			CritChance = 0.2,
			Range = 50,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 60.0,
			BulletLife = 2.0,
		},
		unlocked = 0,
	},
	[10701] = 
	{
		name = 'Crossbow',
		icon = 'crossbow',
		model = 'Crossbow',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.1,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 30.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10702] = 
	{
		name = 'Crossbow',
		icon = 'crossbow',
		model = 'Crossbow',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.1,
			CritChance = 0.05,
			Range = 50,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 30.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10703] = 
	{
		name = 'Crossbow',
		icon = 'crossbow',
		model = 'Crossbow',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.1,
			CritChance = 0.1,
			Range = 50,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 30.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
	[10704] = 
	{
		name = 'Crossbow',
		icon = 'crossbow',
		model = 'Crossbow',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 50,
		attr = 
		{
			Damage = 100,
			AttackSpeed = 1.1,
			CritChance = 0.2,
			Range = 50,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 10,
			BulletSpeed = 30.0,
			BulletLife = 1.5,
		},
		unlocked = 0,
	},
}
return config