local config = 
{
	[10101] = 
	{
		name = 'weapon1',
		icon = 'weapon1',
		model = 'weapon1',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.67,
			CritChance = 0.3,
			Range = 200,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10102] = 
	{
		name = 'weapon1',
		icon = 'weapon1',
		model = 'weapon1',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 39,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.57,
			CritChance = 0.3,
			Range = 200,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10103] = 
	{
		name = 'weapon1',
		icon = 'weapon1',
		model = 'weapon1',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 74,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.5,
			CritChance = 0.3,
			Range = 200,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10104] = 
	{
		name = 'weapon1',
		icon = 'weapon1',
		model = 'weapon1',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 149,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.34,
			CritChance = 0.3,
			Range = 200,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10201] = 
	{
		name = 'weapon2',
		icon = 'weapon2',
		model = 'weapon2',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 10,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.76,
			CritChance = 0.1,
			Range = 150,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 15,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10202] = 
	{
		name = 'weapon2',
		icon = 'weapon2',
		model = 'weapon2',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 22,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.7,
			CritChance = 0.1,
			Range = 150,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 15,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10203] = 
	{
		name = 'weapon2',
		icon = 'weapon2',
		model = 'weapon2',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 45,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.67,
			CritChance = 0.1,
			Range = 150,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 15,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10204] = 
	{
		name = 'weapon2',
		icon = 'weapon2',
		model = 'weapon2',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 91,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.56,
			CritChance = 0.1,
			Range = 150,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 15,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10301] = 
	{
		name = 'weapon3',
		icon = 'weapon3',
		model = 'weapon3',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 46,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.67,
			CritChance = 0.05,
			Range = 175,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10302] = 
	{
		name = 'weapon3',
		icon = 'weapon3',
		model = 'weapon3',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 46,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.67,
			CritChance = 0.05,
			Range = 175,
			LifeSteal = 0.45,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10303] = 
	{
		name = 'weapon3',
		icon = 'weapon3',
		model = 'weapon3',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 86,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.61,
			CritChance = 0.1,
			Range = 175,
			LifeSteal = 0.5,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[10304] = 
	{
		name = 'weapon3',
		icon = 'weapon3',
		model = 'weapon3',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 173,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.56,
			CritChance = 0.2,
			Range = 175,
			LifeSteal = 0.6,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20101] = 
	{
		name = 'crossbow1',
		icon = 'crossbow1',
		model = 'crossbow1',
		type = 2,
		rarity = 1,
		class = 1,
		base_price = 18,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.13,
			CritChance = 0.3,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 1.5,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20102] = 
	{
		name = 'crossbow1',
		icon = 'crossbow1',
		model = 'crossbow1',
		type = 2,
		rarity = 2,
		class = 1,
		base_price = 36,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.13,
			CritChance = 0.35,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 1.75,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20103] = 
	{
		name = 'crossbow1',
		icon = 'crossbow1',
		model = 'crossbow1',
		type = 2,
		rarity = 3,
		class = 1,
		base_price = 66,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.13,
			CritChance = 0.4,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20104] = 
	{
		name = 'crossbow1',
		icon = 'crossbow1',
		model = 'crossbow1',
		type = 2,
		rarity = 4,
		class = 1,
		base_price = 140,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.13,
			CritChance = 0.45,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.25,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20201] = 
	{
		name = 'crossbow2',
		icon = 'crossbow2',
		model = 'crossbow2',
		type = 2,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.37,
			CritChance = 0.03,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20202] = 
	{
		name = 'crossbow2',
		icon = 'crossbow2',
		model = 'crossbow2',
		type = 2,
		rarity = 2,
		class = 1,
		base_price = 39,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.28,
			CritChance = 0.03,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20203] = 
	{
		name = 'crossbow2',
		icon = 'crossbow2',
		model = 'crossbow2',
		type = 2,
		rarity = 3,
		class = 1,
		base_price = 74,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.2,
			CritChance = 0.03,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20204] = 
	{
		name = 'crossbow2',
		icon = 'crossbow2',
		model = 'crossbow2',
		type = 2,
		rarity = 4,
		class = 1,
		base_price = 149,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 1.12,
			CritChance = 0.03,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 8,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20301] = 
	{
		name = 'crossbow3',
		icon = 'crossbow3',
		model = 'crossbow3',
		type = 2,
		rarity = 1,
		class = 1,
		base_price = 56,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.12,
			CritChance = 0.0,
			Range = 300,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20302] = 
	{
		name = 'crossbow3',
		icon = 'crossbow3',
		model = 'crossbow3',
		type = 2,
		rarity = 2,
		class = 1,
		base_price = 56,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.12,
			CritChance = 0.0,
			Range = 300,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20303] = 
	{
		name = 'crossbow3',
		icon = 'crossbow3',
		model = 'crossbow3',
		type = 2,
		rarity = 3,
		class = 1,
		base_price = 103,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.12,
			CritChance = 0.0,
			Range = 350,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
	[20304] = 
	{
		name = 'crossbow3',
		icon = 'crossbow3',
		model = 'crossbow3',
		type = 2,
		rarity = 4,
		class = 1,
		base_price = 207,
		attr = 
		{
			Damage = 50,
			AttackSpeed = 0.09,
			CritChance = 0.0,
			Range = 400,
			LifeSteal = 0.0,
			CritDamage = 2.0,
			Knockback = 0,
			BulletSpeed = 0.1,
			BulletLife = 0.9,
		},
		unlocked = 0,
	},
}
return config