local config = 
{
	[10101] = 
	{
		name = 'Pistol',
		model = 'Pistol',
		icon = 'pistol',
		fire_audio = 'weapon_pistol_1',
		hit_audio = 'bullet_hit_1',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.3,
			CritDamage = 2.0,
			Range = 200,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10102] = 
	{
		name = 'Pistol',
		model = 'Pistol',
		icon = 'pistol',
		fire_audio = 'weapon_pistol_1',
		hit_audio = 'bullet_hit_2',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.3,
			CritDamage = 2.0,
			Range = 200,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10103] = 
	{
		name = 'Pistol',
		model = 'Pistol',
		icon = 'pistol',
		fire_audio = 'weapon_pistol_2',
		hit_audio = 'bullet_hit_3',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.3,
			CritDamage = 2.0,
			Range = 200,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10104] = 
	{
		name = 'Pistol',
		model = 'Pistol',
		icon = 'pistol',
		fire_audio = 'weapon_pistol_2',
		hit_audio = 'bullet_hit_4',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.3,
			CritDamage = 2.0,
			Range = 200,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10201] = 
	{
		name = 'Shotgun',
		model = 'Shotgun',
		icon = 'shotgun',
		fire_audio = 'weapon_shotgun_1',
		hit_audio = 'bullet_hit_5',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 1.5,
			Range = 150,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 12.0,
		},
		unlocked = 0,
	},
	[10202] = 
	{
		name = 'Shotgun',
		model = 'Shotgun',
		icon = 'shotgun',
		fire_audio = 'weapon_shotgun_2',
		hit_audio = 'bullet_hit_6',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 1.5,
			Range = 150,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 12.0,
		},
		unlocked = 0,
	},
	[10203] = 
	{
		name = 'Shotgun',
		model = 'Shotgun',
		icon = 'shotgun',
		fire_audio = 'weapon_shotgun_3',
		hit_audio = 'bullet_hit_7',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 1.5,
			Range = 150,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 12.0,
		},
		unlocked = 0,
	},
	[10204] = 
	{
		name = 'Shotgun',
		model = 'Shotgun',
		icon = 'shotgun',
		fire_audio = 'weapon_shotgun_4',
		hit_audio = 'bullet_hit_8',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 1.5,
			Range = 150,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 12.0,
		},
		unlocked = 0,
	},
	[10301] = 
	{
		name = 'SMG',
		model = 'SMG',
		icon = 'smg',
		fire_audio = 'weapon_smg_1',
		hit_audio = 'bullet_hit_1',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10302] = 
	{
		name = 'SMG',
		model = 'SMG',
		icon = 'smg',
		fire_audio = 'weapon_smg_2',
		hit_audio = 'bullet_hit_2',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10303] = 
	{
		name = 'SMG',
		model = 'SMG',
		icon = 'smg',
		fire_audio = 'weapon_smg_3',
		hit_audio = 'bullet_hit_3',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10304] = 
	{
		name = 'SMG',
		model = 'SMG',
		icon = 'smg',
		fire_audio = 'weapon_smg_4',
		hit_audio = 'bullet_hit_4',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.2,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10401] = 
	{
		name = 'Sniper',
		model = 'Sniper',
		icon = 'sniper',
		fire_audio = 'weapon_sniper_1',
		hit_audio = 'bullet_hit_5',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10402] = 
	{
		name = 'Sniper',
		model = 'Sniper',
		icon = 'sniper',
		fire_audio = 'weapon_sniper_1',
		hit_audio = 'bullet_hit_6',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10403] = 
	{
		name = 'Sniper',
		model = 'Sniper',
		icon = 'sniper',
		fire_audio = 'weapon_sniper_2',
		hit_audio = 'bullet_hit_7',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10404] = 
	{
		name = 'Sniper',
		model = 'Sniper',
		icon = 'sniper',
		fire_audio = 'weapon_sniper_2',
		hit_audio = 'bullet_hit_8',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.2,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10501] = 
	{
		name = 'Minigun',
		model = 'Minigun',
		icon = 'minigun',
		fire_audio = 'weapon_minigun',
		hit_audio = 'bullet_hit_1',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10502] = 
	{
		name = 'Minigun',
		model = 'Minigun',
		icon = 'minigun',
		fire_audio = 'weapon_minigun',
		hit_audio = 'bullet_hit_2',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10503] = 
	{
		name = 'Minigun',
		model = 'Minigun',
		icon = 'minigun',
		fire_audio = 'weapon_minigun',
		hit_audio = 'bullet_hit_3',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10504] = 
	{
		name = 'Minigun',
		model = 'Minigun',
		icon = 'minigun',
		fire_audio = 'weapon_minigun',
		hit_audio = 'bullet_hit_4',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.2,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10601] = 
	{
		name = 'Rocket',
		model = 'Rocket',
		icon = 'rocket',
		fire_audio = 'weapon_rocket',
		hit_audio = 'bullet_rocket',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 15.0,
		},
		unlocked = 0,
	},
	[10602] = 
	{
		name = 'Rocket',
		model = 'Rocket',
		icon = 'rocket',
		fire_audio = 'weapon_rocket',
		hit_audio = 'bullet_rocket',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 15.0,
		},
		unlocked = 0,
	},
	[10603] = 
	{
		name = 'Rocket',
		model = 'Rocket',
		icon = 'rocket',
		fire_audio = 'weapon_rocket',
		hit_audio = 'bullet_rocket',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 15.0,
		},
		unlocked = 0,
	},
	[10604] = 
	{
		name = 'Rocket',
		model = 'Rocket',
		icon = 'rocket',
		fire_audio = 'weapon_rocket',
		hit_audio = 'bullet_rocket',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.2,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 15.0,
		},
		unlocked = 0,
	},
	[10701] = 
	{
		name = 'Crossbow',
		model = 'Crossbow',
		icon = 'crossbow',
		fire_audio = 'weapon_crossbow',
		hit_audio = 'bullet_crossbow',
		type = 1,
		rarity = 1,
		class = 1,
		base_price = 20,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10702] = 
	{
		name = 'Crossbow',
		model = 'Crossbow',
		icon = 'crossbow',
		fire_audio = 'weapon_crossbow',
		hit_audio = 'bullet_crossbow',
		type = 1,
		rarity = 2,
		class = 1,
		base_price = 40,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.05,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10703] = 
	{
		name = 'Crossbow',
		model = 'Crossbow',
		icon = 'crossbow',
		fire_audio = 'weapon_crossbow',
		hit_audio = 'bullet_crossbow',
		type = 1,
		rarity = 3,
		class = 1,
		base_price = 60,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.1,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
	[10704] = 
	{
		name = 'Crossbow',
		model = 'Crossbow',
		icon = 'crossbow',
		fire_audio = 'weapon_crossbow',
		hit_audio = 'bullet_crossbow',
		type = 1,
		rarity = 4,
		class = 1,
		base_price = 150,
		attr = 
		{
			Damage = 100,
			MeleeDamage = 1.0,
			RangedDamage = 1.0,
			AttackSpeed = 0.8,
			CritChance = 0.2,
			CritDamage = 2.0,
			Range = 175,
			LifeSteal = 0.1,
			Knockback = 10,
			BulletSpeed = 100.0,
			BulletLife = 1.2,
			BulletRange = 0.0,
		},
		unlocked = 0,
	},
}
return config